drop table if exists Users,Branches,Employees,Requests,Answers;

create table if not exists Users (
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20),
    email varchar(200),
    phone_number varchar(11),
    CONSTRAINT user_FK PRIMARY KEY (user_id)
);

create table if not exists Branches (
    brach_id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20),
    address varchar(20),
    phone varchar(11),
    CONSTRAINT Br_FK PRIMARY KEY (brach_id)
);

create table if not exists Employees (
    employee_id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20),
    phone_number varchar(11),
    title varchar(50),
    availability boolean,
    CONSTRAINT empl_FK PRIMARY KEY (employee_id)
);

create table if not exists Requests (
    ticket_id int GENERATED BY DEFAULT AS IDENTITY,
    employee_id int references Employees(employee_id) on delete CASCADE,
    user_id int references Users(user_id) on delete CASCADE,
    description varchar(50),
    status varchar(50),
    data_create timestamp,
    close_date timestamp,
    CONSTRAINT req_FK PRIMARY KEY (ticket_id)
);

create table if not exists Answers (
    answer_id int GENERATED BY DEFAULT AS IDENTITY,
    employee_id int references Employees(employee_id) on delete CASCADE,
    description varchar(100),
    data_of_response timestamp,
    CONSTRAINT ans_FK PRIMARY KEY (answer_id)
);


