create table if not exists Users (
    user_id int primary key GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20),
    email varchar(200),
    phone_number varchar(11)
);

create table if not exists Branches (
    brach_id int primary key GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20),
    address varchar(20),
    phone varchar(11)
);

create table if not exists Employees (
    employee_id int primary key GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20),
    phone_number varchar(11),
    title varchar(50),
    availability boolean
);

create table if not exists Requests (
    ticket_id int primary key GENERATED BY DEFAULT AS IDENTITY,
    employee_id int references Employees(employee_id),
    user_id int references Users(user_id),
    desckription varchar(50),
    status varchar(50),
    data_create timestamp,
    close_date timestamp

);

create table if not exists Answers (
    answer_id int primary key GENERATED BY DEFAULT AS IDENTITY,
    employee_id int references Employees(employee_id),
    description varchar(100),
    data_of_response timestamp
);